---
- name: Including default ntp-server list.
  include_vars: "{{ ansible_os_family }}_base_packages.yml"

- name: Install base packages
  package:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ base_packages }}"

- name: Install ESXI VM Tools
  package:
    name: open-vm-tools
    state: present
    update_cache: true
  when: COMMOM_VM_HOST == "ESXi"

- name: Install ESXI VM Tools
  package:
    name: qemu-guest-agent
    state: present
    update_cache: true
  when: COMMOM_VM_HOST == "Proxmox"
