---
- name: Add the Debian required repositories.
  apt_repository:
    repo: "{{ item.repo }}"
    filename: "{{ item.file }}"
    state: present
  with_items:
    - repo: deb http://deb.debian.org/debian/ stretch-backports main contrib non-free
      file: backports
    - repo: deb http://deb.debian.org/debian/ stretch non-free
      file: non-free
  when: ansible_distribution == 'Debian'

- name: Install base packages
  package:
    name: "{{ COMMON_BASE_PACKAGES }}"
    state: present
    update_cache: true

- name: Install ESXI VM Tools
  package:
    name: open-vm-tools
    state: present
    update_cache: true
  when: COMMON_VM_HOST == "VMware"

- name: Install kvm (Proxmox) VM Tools
  package:
    name: qemu-guest-agent
    state: present
    update_cache: true
  when: COMMON_VM_HOST == "kvm"
