---
- name: Install base packages
  apt:
    name: "{{ COMMON_BASE_PACKAGES }}"
    state: present
    update_cache: true

- name: Install ESXI VM Tools
  apt:
    name: open-vm-tools
    state: present
    update_cache: true
  when: COMMON_VM_HOST == "VMware"

- name: Install kvm (Proxmox) VM Tools
  apt:
    name: qemu-guest-agent
    state: present
    update_cache: true
  when: COMMON_VM_HOST == "kvm"
