---
- name: Update hostname with inventory hostname.
  hostname:
    name: "{{ inventory_hostname_short }}"
  tags: molecule-notest

- name: Fix /etc/hosts removing the old hostname
  lineinfile:
    state: present
    dest: /etc/hosts
    line: "127.0.1.1 {{ inventory_hostname }} {{ inventory_hostname_short }} localhost"
    regexp: "^127.0.1.1"
  tags: molecule-notest
