---
- name: Update hostname with inventory hostname.
  hostname:
    name: "{{ inventory_hostname | regex_replace('\\.[-a-zA-Z0-9_.]*') }}"
  tags: molecule-notest

- name: Fix /etc/hosts removing the old hostname
  lineinfile:
    state: present
    dest: /etc/hosts
    line: "{{ ansible_default_ipv4.address }} {{ inventory_hostname }} {{ ansible_hostname }}"
    regexp: "^{{ ansible_default_ipv4.address }}"
