---
- name: Update hostname with inventory hostname.
  hostname:
    name: "{{ inventory_hostname_short }}"
  tags: molecule-notest

- name: Fix /etc/hosts removing the old hostname
  lineinfile:
    state: present
    dest: /etc/hosts
    line: "{{ ansible_default_ipv4.address }} {{ inventory_hostname }} {{ inventory_hostname_short }}"
    regexp: "^{{ ansible_default_ipv4.address }}"
  tags: molecule-notest
