---
- name: Including os related vars.
  include_vars: "os/{{ ansible_distribution }}.yml"

- include: set-dns.yml
  when: ansible_distribution == 'Debian'

- include: "base-packages.yml"
  when: COMMON_DEPLOY_BASE_PACKAGES

- include: ntp.yml
  when: COMMON_DEPLOY_NTP

- include: hostname.yml
