---
- name: Including default ntp-server list.
  include_vars: ntp.yml

- name: Install ntp.
  package:
     name: ntp
     state: present

- name: Configure ntp.
  template:
     src: ntp/ntp.conf.j2
     dest: /etc/ntp.conf
  notify: restart ntp

- name: Enable ntp.
  service:
     name: "{{ ntp_service }}"
     state: started
     enabled: true
