---
- name: restart chronyd
  service:
    name: "{{ chrony_deamon }}"
    state: restarted
    enabled: true

- name: Reload Networking
  service:
    name: networking
    state: restarted
  when: ansible_os_family == 'Debian'

- name: Reload Networking
  service:
    name: NetworkManager
    state: reloaded
  when: ansible_os_family == 'RedHat'
