---
- name: restart ntp
  service:
    name: "{{ ntp_service }}"
    state: restarted
    enabled: true

- name: restart network
  service:
    name: networking
    state: restarted
    enabled: true
