---
- name: restart chronyd
  service:
    name: "{{ chrony_deamon }}"
    state: restarted
    enabled: true

- name: restart network
  service:
    name: networking
    state: restarted
    enabled: true
